## ----------------------------------------------------------------------
## Instructions
##
## All of the properties in this file are commented out; they have a pound
## symbol at the start of each line that renders them inert.
##
## Instructions and headings are marked with two preceding pound
## symbols (##).
##
## On import, all commented-out properties are ignored, and the
## corresponding values in the destination environment remain
## unchanged.
##
## To set or change a property on import using this file,
## uncomment the property by removing the pound symbol from the start
## of its line. Then enter a value for the property after the equals
## sign (=) at the end of that import customization file.
##
## If you uncomment a property, but provide no value, the value of
## that property will be set to null in the destination environment.
## Properties that correspond to admin console settings and require a value
## will be set to their default value instead of being set to null. Default
## values of settings may be different between versions of Appian.
##
## To force sync of a record type please add an entry to the file in the following format
## recordType.<UUID>.forceSync=true
##
## To force import unchanged objects add the following line in the file
## importSetting.FORCE_UPDATE=true
##
## Note: Never remove the double pound symbols (##) in front of instructions
## and headings.
## ----------------------------------------------------------------------
recordType.375b5168-be37-4734-8060-52490d545f26.forceSync=true
recordType.9bff5542-7902-4d4d-a723-579d7add597d.forceSync=true
recordType.765820b0-4dde-40e3-9604-06a6096aa4ce.forceSync=true
recordType.347dfce2-5c7f-49a3-b55a-fd7c92a61d6b.forceSync=true

## Constant: IEM_ICO_ENV_SERVER_ENVIRONMENT
## Type: Text
##
## Text values will be displayed in Appian exactly as they are
## specified here. No spaces are trimmed. Values do not need to be
## encased in quotation marks.
content._a-0000eb49-2433-8000-af2a-01ef9001ef90_34633.VALUE=TEST