<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types:IEM_ICO"
  xmlns:tns="urn:com:appian:types:IEM_ICO" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="IEM_ICO_UTY_Object">
    <xsd:annotation>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000eaca-b073-8000-45e8-014d98014d98</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0000eaca-b073-8000-45e8-014d98014d98"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
      <xsd:documentation><![CDATA[Standard utility data type for object references.]]></xsd:documentation>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="objectId" nillable="true" type="xsd:int"/>
      <xsd:element name="objectTypeId" nillable="true" type="xsd:int"/>
      <xsd:element name="objectName" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(length=255)</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
