<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema targetNamespace="urn:com:appian:types:IEM_ICO"
  xmlns:tns="urn:com:appian:types:IEM_ICO" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:complexType name="IEM_ICO_UTY_ButtonTab">
    <xsd:annotation>
      <xsd:appinfo source="http://www.appian.com/ae/types/2009">
        <ns2:Metadata xmlns:ns2="http://www.appian.com/ae/types/2009">
          <ns2:versionUuid>0000ef37-02fd-8000-bcb0-014d98014d98</ns2:versionUuid>
          <ns2:history>
            <ns2:historyInfo versionUuid="0000ef37-02fd-8000-bcb0-014d98014d98"/>
          </ns2:history>
        </ns2:Metadata>
      </xsd:appinfo>
    </xsd:annotation>
    <xsd:sequence>
      <xsd:element name="index" nillable="true" type="xsd:int">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Id</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="label" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(length=55)</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="accessibilityText" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(length=255)</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="helpTooltip" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(length=255)</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="icon" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(length=55)</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="iconPosition" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(length=255)</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="style" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(length=255)</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="color" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(length=255)</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="width" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(length=255)</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="size" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(length=255)</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
      <xsd:element name="isBookmarked" nillable="true" type="xsd:boolean"/>
      <xsd:element name="isDisabled" nillable="true" type="xsd:boolean"/>
      <xsd:element name="isSubmit" nillable="true" type="xsd:boolean"/>
      <xsd:element name="isValidate" nillable="true" type="xsd:boolean"/>
      <xsd:element name="showWhen" nillable="true" type="xsd:boolean"/>
      <xsd:element name="validationGroup" nillable="true" type="xsd:string">
        <xsd:annotation>
          <xsd:appinfo source="appian.jpa">@Column(length=255)</xsd:appinfo>
        </xsd:annotation>
      </xsd:element>
    </xsd:sequence>
  </xsd:complexType>
</xsd:schema>
