name: DEPLOY APPIAN PACKAGES

on: 
  workflow_dispatch:
    inputs:
      commit_sha:
        description: "Commit SHA to cherry-pick"
        required: false
        type: string

  push:
    branches:
      - test
      - main
      
jobs:
  deploy-appian:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code 
        uses: actions/checkout@v4 
        with:
          fetch-depth: 0

      - name: Set Git Comparison Range
        shell: bash
        run: |
          if [ "${{ github.event_name }}" = "workflow_dispatch" ] && [ -n "${{inputs.commit_sha}}" ]; then
            echo "BEFORE_SHA=$(git rev-parse HEAD)" >> "$GITHUB_ENV"
          else
            echo "BEFORE_SHA=${{ github.event.before }}" >> "$GITHUB_ENV"
            echo "AFTER_SHA=${{ github.sha }}" >> "$GITHUB_ENV"
          fi
      - name: Cherry-pick Selected Commit
        if: ${{ github.event_name == 'workflow_dispatch' && inputs.commit_sha != '' }}
        shell: bash
        run: |
          COMMIT_SHA="${{ inputs.commit_sha }}"
          echo "Fetching commit history..."
          git fetch origin --prune
          echo "Cherry-picking commit: $COMMIT_SHA"
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git cherry-pick "$COMMIT_SHA"
          echo "AFTER_SHA=$(git rev-parse HEAD)" >> "GITHUB_ENV"
          echo "Cherry-pick completed successfully"
      - name: Set Environment Variables 
        run: |
          if [ "${GITHUB_REF_NAME}" = "test" ]; then
            echo "APP_URL=${{ vars.CALI_DEV_URL }}" >> $GITHUB_ENV
            echo "APPIAN_API_KEY=${{ secrets.TEST_APPIAN_API_KEY }}" >> $GITHUB_ENV 
            echo "DB_HOST=${{ vars.CALI_DEV_DB_HOST }}" >> $GITHUB_ENV
            echo "DB_NAME=${{ vars.CALI_DEV_DB_NAME }}" >> $GITHUB_ENV 
            echo "DB_PORT=${{ vars.DB_PORT }}" >> $GITHUB_ENV
            echo "DB_USER=${{ vars.DB_USER }}" >> $GITHUB_ENV
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
            
          elif [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "APP_URL=${{ vars.CALI_URL }}" >> $GITHUB_ENV
            echo "APPIAN_API_KEY=${{ secrets.PROD_APPIAN_API_KEY }}" >> $GITHUB_ENV
            echo "DB_HOST=${{ vars.CALI_DB_HOST }}" >> $GITHUB_ENV
            echo "DB_NAME=${{ vars.CALI_DB_NAME }}" >> $GITHUB_ENV 
            echo "DB_PORT=${{ vars.DB_PORT }}" >> $GITHUB_ENV
            echo "DB_USER=${{ vars.DB_USER }}" >> $GITHUB_ENV
            echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> $GITHUB_ENV
          else
            echo "Unsupported branch"
            exit 1
          fi 
      - name: Show Deployment Target
        run: |
          echo "================================================="
          echo "Branch: $GITHUB_REF_NAME"
          echo "APP_URL=$APP_URL"

          if [ "$GITHUB_REF_NAME" = "test" ]; then
            echo "Deploying to CALI DEV"
          elif [ "$GITHUB_REF_NAME" = "main" ]; then
            echo "Deploying to CALI PROD"
          fi
          echo "================================================="          
          
      - name: RUN DIFF - COMPARE CHANGES AND BUILD PACKAGE
        shell: bash
        run: |
          echo "================================"
          echo "Comparing commits:"
          echo: "Before: $BEFORE_SHA"
          echo: "After: $AFTER_SHA"
          echo "================================"

          git diff --name-status "$BEFORE_SHA" "$AFTER_SHA" | tee diff-report.txt
          echo ""
          echo "Added:"
          git diff --diff-filter=A --name-only "$BEFORE_SHA" "$AFTER_SHA" 
          #grep "^Added" diff-report.txt || true
          echo ""
          echo "Modified:"
          git diff --diff-filter=M --name-only "$BEFORE_SHA" "$AFTER_SHA" 
          #grep "^Modified" diff-report.txt || true
          echo ""
          echo "Deleted:"
          git diff --diff-filter=D --name-only "$BEFORE_SHA" "$AFTER_SHA" 
          #grep "^Deleted" diff-report.txt || true
          echo ""
          echo "Creating Deployment Package"
          echo ""
          echo "Files included in deployment package:"
          find application content datatype group groupType META-INF processModel processModelFolder recordType -type f | sort
          zip -r appian-package.zip \
            application \
            content \
            datatype \
            group \
            groupType \
            META-INF \
            processModel \
            processModelFolder \
            recordType \
            patches \
            -x ".git/*" \
               ".github/*" \
               "README.md"
               
          echo "========= ZIP CHECK ============="
          pwd
          ls -lah
          find . -name "appian-package.zip"

          if [ -f appian-package.zip ]; then
            echo "ZIP EXISTS"
            ls -lh appian-package.zip
          else
            echo "ZIP NOT FOUND"
            exit 1
          fi
          echo "PACKAGE_FILE=appian-package.zip" >> $GITHUB_ENV
  
          PROPERTIES_FILES=$(find . -maxdepth 1 -name "*.properties" | head -n 1 | sed 's|^\./||')
          SQL_FILE=$(find . -maxdepth 1 -name "*.sql" | head -n 1 | sed 's|^\./||')
          echo "PROPERTIES_FILES=$PROPERTIES_FILES" >> $GITHUB_ENV
          echo "SQL_FILE=$SQL_FILE" >> $GITHUB_ENV
          echo "Selected properties file: $PROPERTIES_FILES"
          echo "Selected SQL file: $SQL_FILE"
          echo "ALL PROPERTIES FILES:"
          find . -maxdepth 1 -name "*.properties"
          echo "ALL SQL FILES:"
          find . -maxdepth 1 -name "*.sql"
          echo ""
          echo "Package Created:"
          ls -lh appian-package.zip
          
      - name: Upload Deployment Package
        env:
          PACKAGE_FILE: ${{ env.PACKAGE_FILE }}
          PROPERTIES_FILES: ${{ env.PROPERTIES_FILES }}
          SQL_FILE: ${{ env.SQL_FILE }}
          
        run: |
        
          echo "PACKAGE_FILE=$PACKAGE_FILE" 
          echo "PROPERTIES_FILES=$PROPERTIES_FILES" 
          echo "SQL_FILE=$SQL_FILE"

          if [ ! -f "$PACKAGE_FILE" ]; then
            echo "Package file not found: $PACKAGE_FILE"
            exit 1
          fi

          JSON_BODY=$(cat <<EOF
          {
            "name":"GitHub Deployment",
            "packageFileName":"$PACKAGE_FILE",
            "customizationFileName":"$PROPERTIES_FILES",
            "dataSource":"jdbc/Appian",
            "databaseScripts":[
              {
                "fileName":"$SQL_FILE",
                "orderId":1
              }
             ]
            }
          EOF
          )
          echo "============= JSON BODY =================="
          echo "$JSON_BODY"
          
          RESPONSE=$(curl -v -X POST "$APP_URL/suite/deployment-management/v2/deployments" \
            -H "Appian-API-Key: $APPIAN_API_KEY" \
            -F "json=$JSON_BODY;type=application/json" \
            -F "file=@$PACKAGE_FILE" \
            -F "file=@$PROPERTIES_FILES" \
            -F "file=@$SQL_FILE"
            )
                                  
          echo "UPLOAD RESPONSE:"
          echo "$RESPONSE"
