name: Deploy SQL to CALI DEV

on:
  workflow_dispatch:

jobs:
  deploy-sql:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Verify Files
        run: ls -la

      - name: Install MySQL Client
        run: |
          sudo apt-get update
          sudo apt-get install -y mysql-client
      - name: Debug DB Connection 
        run: |
          echo "HOST=${{ secrets.DB_HOST }}"
          echo "PORT=${{ secrets.DB_PORT }}"
          echo "USER=${{ secrets.DB_USER }}"
          echo "DB=${{ secrets.DB_NAME }}"

          mysql \
            --host="${{ secrets.DB_HOST }}" \
            --port="${{ secrets.DB_PORT }}" \
            --user="USER=${{ secrets.DB_USER }}" \
            --password="${{ secrets.DB_PASSWORD }}" \
            --database="${{ secrets.DB_NAME }}" \
            -e "SHOW DATABASES;"
