name: Deploy from CALI DEV -> CALI

on:
  push:
    branches:
    - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
      
    - name: Checkout
      run: |
        curl -X POST "https://cali-dev.iem-digital.com/suite/deployment-api/v1/import" \
        -H "Authorization: Bearer ${{  secrets.APPIAN_API_KEY }}" \
        -H "Content-Type: multipart/from-data" \
        -F "appPackage=@appian-file.zip"


