name: Deploy from CALI DEV -> CALI

on:
  push:
    branches:
    - main
    
jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout Code
      uses: actions/checkout@v3
    - name: Debug file
      run: ls -la

    - name: Create test file
      run: |
        echo "hello Appian from GitHub" > test2.txt
        ls -la
        
    - name: Debug API key length
      env:
        APPIAN_API_KEY: ${{ secrets.APPIAN_API_KEY }}
      run: |
        echo "API KEY LENGTH=${#APPIAN_API_KEY}"
        
    - name: Upload file to CALI-DEV
      id: token
      run: |
        RESPONSE=$(curl -v -X POST "${{ secrets.APP_URL }}/suite/deployment-management/v2/deployments" \
          -H "Appian-API-Key: ${{  secrets.APPIAN_API_KEY }}" \
          -F 'json={"name":"Test Deployment"};type=application/json' \
          -F "file=@test2.txt")

        echo "UPLOAD RESPONSE:"
        echo "$RESPONSE"
      



